[build]
  publish = "static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/data/*"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
